### ISSUE TITLE
ValueError("Cannot load file containing pickled data")

### ISSUE THREAD

**Issue by mollnn** [mollnn/yet-another-video-caption#1]
训练过程中遇到了错误

新轮次 42 正在训练……
  0%|                                                                                                                                                      | 0/100 [00:00<?, ?it/s]/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/nn/functional.py:1340: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
 67%|██████████████████████████████████████████████████████████████████████████████████████████████▍                                              | 67/100 [00:13<00:11,  2.78it/s]Traceback (most recent call last):
  File "train.py", line 245, in <module>
    main(opt)
  File "train.py", line 232, in main
    optimizer, exp_lr_scheduler, opt, rl_crit)
  File "train.py", line 130, in train
    for data in tqdm(loader):
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/yavc/dataloader.py", line 61, in __getitem__
    fc_feat.append(np.load(os.path.join(dir, 'G_%05d.npy' % (ix))))
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 457, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
 67%|██████████████████████████████████████████████████████████████████████████████████████████████▍                                              | 67/100 [00:13<00:06,  4.98it/s]

记得找个时间修

**Comment by mollnn** [comment]
已修复
